export {default as session} from './session/reducer';
export {default as formLogin} from './forms/form-login/reducer';
export {default as tasks} from './tasks/reducer';
export {default as priority} from './priority/reducer';
export {default as statuses} from './statuses/reducer';
export {default as formCreateTask} from './forms/form-create-task/reducer';
export {default as formUpdateTask} from './forms/form-update-task/reducer';
export {default as taskFilter} from './task-filter/reducer';
export {default as viewSelect} from './view-select/reducer';